# Generated by Django 5.2.5 on 2025-09-28 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Incorrect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField()),
                ('correct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.correct')),
            ],
        ),
    ]
